//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.07 at 05:31:23 PM YEKT 
//


package me.osm.osmdoc.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the me.osm.osmdoc.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Feature_QNAME = new QName("http://map.osm.me/osm-doc-part", "feature");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: me.osm.osmdoc.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Tag }
     * 
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link Tag.Val }
     * 
     */
    public Tag.Val createTagVal() {
        return new Tag.Val();
    }

    /**
     * Create an instance of {@link Feature }
     * 
     */
    public Feature createFeature() {
        return new Feature();
    }

    /**
     * Create an instance of {@link Tags }
     * 
     */
    public Tags createTags() {
        return new Tags();
    }

    /**
     * Create an instance of {@link KeyType }
     * 
     */
    public KeyType createKeyType() {
        return new KeyType();
    }

    /**
     * Create an instance of {@link Choise }
     * 
     */
    public Choise createChoise() {
        return new Choise();
    }

    /**
     * Create an instance of {@link Fref }
     * 
     */
    public Fref createFref() {
        return new Fref();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link MoreTags }
     * 
     */
    public MoreTags createMoreTags() {
        return new MoreTags();
    }

    /**
     * Create an instance of {@link DocPart }
     * 
     */
    public DocPart createDocPart() {
        return new DocPart();
    }

    /**
     * Create an instance of {@link me.osm.osmdoc.model.Trait }
     * 
     */
    public me.osm.osmdoc.model.Trait createTrait() {
        return new me.osm.osmdoc.model.Trait();
    }

    /**
     * Create an instance of {@link Hierarchy }
     * 
     */
    public Hierarchy createHierarchy() {
        return new Hierarchy();
    }

    /**
     * Create an instance of {@link Group }
     * 
     */
    public Group createGroup() {
        return new Group();
    }

    /**
     * Create an instance of {@link LangString }
     * 
     */
    public LangString createLangString() {
        return new LangString();
    }

    /**
     * Create an instance of {@link Feature.Trait }
     * 
     */
    public Feature.Trait createFeatureTrait() {
        return new Feature.Trait();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Feature }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://map.osm.me/osm-doc-part", name = "feature")
    public JAXBElement<Feature> createFeature(Feature value) {
        return new JAXBElement<Feature>(_Feature_QNAME, Feature.class, null, value);
    }

}
