//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.07 at 05:31:23 PM YEKT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://map.osm.me/osm-doc-part", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package me.osm.osmdoc.model;
